// this module is includes code that is generated by build.rs into mod.rs (to be compiled by cargo into a library)
#[cfg(feature = "cpp_wrapper")]
mod glue_cpp {
    #![allow(
        clippy::enum_variant_names,
        clippy::unused_unit,
        clippy::blacklisted_name,
        clippy::let_unit_value,
        clippy::not_unsafe_ptr_arg_deref,
        clippy::borrowed_box
    )]
    include!(concat!(env!("OUT_DIR"), "/glue_cpp.rs"));
}

#[cfg(feature = "java_wrapper")]
mod glue_java {
    #![allow(
        clippy::enum_variant_names,
        clippy::unused_unit,
        clippy::let_and_return,
        clippy::not_unsafe_ptr_arg_deref,
        clippy::cast_lossless,
        clippy::blacklisted_name,
        clippy::too_many_arguments,
        clippy::trivially_copy_pass_by_ref,
        clippy::let_unit_value,
        clippy::clone_on_copy
    )]
    include!(concat!(env!("OUT_DIR"), "/glue_java.rs"));
}
